[supervisord]
nodaemon=true
logfile=/workspace/logs/supervisord.log
logfile_maxbytes=10MB
pidfile=/workspace/supervisord.pid
loglevel=info

[unix_http_server]
file=/workspace/supervisord.sock

[supervisorctl]
serverurl=unix:///workspace/supervisord.sock

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[program:comfyui]
command=python3 main.py --listen 0.0.0.0 --port %(ENV_COMFY_PORT)s --disable-auto-launch --gpu-only
directory=/comfyui
autostart=true
autorestart=true
startretries=5
startsecs=10
stdout_logfile=/workspace/comfyui.log
stdout_logfile_maxbytes=50MB
stderr_redirect_stderr=true
environment=COMFY_PORT="%(ENV_COMFY_PORT)s"

[program:admin]
command=python3 -u server.py
directory=/workspace/admin
autostart=true
autorestart=true
startretries=5
startsecs=5
stdout_logfile=/workspace/admin.log
stdout_logfile_maxbytes=50MB
stderr_redirect_stderr=true
environment=COMFY_PORT="%(ENV_COMFY_PORT)s",ADMIN_PORT="%(ENV_ADMIN_PORT)s"
