import { z } from 'zod'
import { eq } from 'drizzle-orm'
import { waitUntil } from 'cloudflare:workers'
import { requireAuth } from '../../utils/auth'
import { resolveApiUrl, callRunPod } from '../../utils/ai'
import { submitItemToRunPod } from '../../utils/submitItem'
import { useMediaBucket, readBase64FromR2 } from '../../utils/r2'
import { generations, mediaItems } from '../../database/schema'

const batchSchema = z.object({
  mediaItemIds: z.array(z.string().uuid()).min(1).max(100),
  basePrompt: z.string().optional().default(''),
  audioPrompt: z.string().optional().default(''),
  negativePrompt: z.string().optional().default(''),
  steps: z.number().min(1).max(50).optional().default(20),
  numFrames: z.number().min(25).max(721).optional().default(241),
  width: z.number().min(256).max(1920).optional().default(768),
  height: z.number().min(256).max(1080).optional().default(512),
  fps: z.number().min(8).max(50).optional().default(24),
  loraStrength: z.number().min(0).max(2).optional().default(1.0),
  imageStrength: z.number().min(0).max(1).optional().default(1.0),
  endpoint: z.string().optional(),
})

/**
 * POST /api/generate/image2video-auto-batch
 *
 * Accepts an array of mediaItemIds, creates DB records immediately,
 * and processes all captioning + job submission in the background.
 * Returns instantly so the client never times out.
 */
export default defineEventHandler(async (event) => {
  const user = await requireAuth(event)
  const body = await readBody(event)
  const parsed = batchSchema.safeParse(body)

  if (!parsed.success) {
    throw createError({ statusCode: 400, message: parsed.error.issues[0]?.message || 'Invalid input' })
  }

  const { mediaItemIds, basePrompt, audioPrompt, negativePrompt, steps, numFrames, width, height, fps, loraStrength, imageStrength, endpoint } = parsed.data
  const apiUrl = resolveApiUrl(endpoint)
  const db = useDatabase()
  const now = new Date().toISOString()

  // Create one parent generation for the whole batch
  const genId = crypto.randomUUID()
  await db.insert(generations).values({
    id: genId,
    userId: user.id,
    prompt: basePrompt || `Auto video batch (${mediaItemIds.length} images)`,
    imageCount: mediaItemIds.length,
    status: 'processing',
    createdAt: now,
  })

  // Create a placeholder media item for each image immediately
  const items: { id: string; sourceMediaId: string; status: string }[] = []
  for (const srcId of mediaItemIds) {
    const videoId = crypto.randomUUID()
    await db.insert(mediaItems).values({
      id: videoId,
      generationId: genId,
      type: 'video',
      prompt: 'Processing...',
      status: 'queued',
      metadata: JSON.stringify({
        apiUrl, sourceMediaId: srcId, autoGenerated: true, batchMode: true,
        pendingCaptioning: true,
        params: { basePrompt, audioPrompt, negativePrompt, steps, numFrames, width, height, fps, loraStrength, imageStrength },
      }),
      createdAt: now,
    })
    items.push({ id: videoId, sourceMediaId: srcId, status: 'queued' })
  }

  console.log(`[AutoVideoBatch] Created gen ${genId.slice(0, 8)} with ${items.length} placeholder items`)

  // ═══ Process everything in the background ═══
  waitUntil((async () => {
    const bucket = useMediaBucket(event)

    for (const item of items) {
      try {
        // 1. Read source image from DB/R2
        const src = await db.select({ url: mediaItems.url, prompt: mediaItems.prompt }).from(mediaItems).where(eq(mediaItems.id, item.sourceMediaId)).get()
        if (!src?.url) {
          await db.update(mediaItems).set({ status: 'failed', prompt: 'Source image not found' }).where(eq(mediaItems.id, item.id))
          continue
        }

        let image = ''
        const originalPrompt = src.prompt || ''
        const base64Match = src.url.match(/^data:image\/\w+;base64,(.+)$/)
        if (base64Match) {
          image = base64Match[1]!
        } else if (bucket) {
          image = await readBase64FromR2(bucket, item.sourceMediaId) || ''
        }

        if (!image) {
          await db.update(mediaItems).set({ status: 'failed', prompt: 'Could not read source image' }).where(eq(mediaItems.id, item.id))
          continue
        }

        // 2. Caption + prompt generation (synchronous pod call)
        const captionInput = {
          action: 'image2video_auto',
          image,
          base_prompt: basePrompt,
          original_prompt: originalPrompt,
          audio_prompt: audioPrompt,
          negative_prompt: negativePrompt,
          count: 1,
          steps, num_frames: numFrames,
          width, height, fps,
          lora_strength: loraStrength,
        }

        const result = await callRunPod(captionInput, apiUrl)
        const rawOutput = result.output || {}
        const output = rawOutput.output || rawOutput
        const prompts: string[] = output.prompts || []
        const caption: string = output.caption || ''
        const prompt = prompts[0] || caption || originalPrompt

        // 3. Update the media item with the generated prompt
        const i2vInput = {
          action: 'image2video' as const,
          model: 'ltx2',
          prompt,
          negative_prompt: negativePrompt,
          image,
          width, height,
          num_frames: numFrames,
          steps, fps,
          lora_strength: loraStrength,
          image_strength: imageStrength,
          audio_prompt: audioPrompt || undefined,
          preset: 'random',
        }

        // 4. Save the captioning results to metadata, then submit via shared utility
        await db.update(mediaItems)
          .set({
            prompt,
            metadata: JSON.stringify({ apiUrl, runpodInput: i2vInput, autoGenerated: true, caption, batchMode: true }),
          })
          .where(eq(mediaItems.id, item.id))

        await submitItemToRunPod(db, item.id)
      } catch (e: any) {
        console.error(`[AutoVideoBatch] ❌ Failed processing ${item.id.slice(0, 8)}:`, e.message)
        await db.update(mediaItems).set({ status: 'failed', prompt: `Pipeline error: ${e.message}` }).where(eq(mediaItems.id, item.id)).catch(() => {})
      }
    }

    console.log(`[AutoVideoBatch] Pipeline complete for gen ${genId.slice(0, 8)}`)
  })())

  // Return immediately — items show as "queued" in the UI, cron/background handles the rest
  return {
    generation: { id: genId, status: 'processing', imageCount: mediaItemIds.length },
    items: items.map(i => ({ id: i.id, generationId: genId, type: 'video', prompt: 'Processing...', status: 'queued', url: null })),
  }
})
