import { z } from 'zod'
import { eq } from 'drizzle-orm'
import { waitUntil } from 'cloudflare:workers'
import { requireAuth } from '../../utils/auth'
import { resolveApiUrl, callRunPod } from '../../utils/ai'
import { generations, mediaItems } from '../../database/schema'

const autoVideoSchema = z.object({
  image: z.string().min(100).optional(),
  mediaItemId: z.string().uuid().optional(),
  basePrompt: z.string().optional().default(''),
  audioPrompt: z.string().optional().default(''),
  negativePrompt: z.string().optional().default(''),
  count: z.number().min(1).max(10).optional().default(5),
  steps: z.number().min(1).max(50).optional().default(20),
  numFrames: z.number().min(25).max(721).optional().default(97),
  width: z.number().min(256).max(1920).optional().default(1280),
  height: z.number().min(256).max(1080).optional().default(720),
  fps: z.number().min(8).max(50).optional().default(24),
  loraStrength: z.number().min(0).max(2).optional().default(1.0),
  endpoint: z.string().optional(),
}).refine(d => d.image || d.mediaItemId, { message: 'Either image (base64) or mediaItemId is required' })

export default defineEventHandler(async (event) => {
  const user = await requireAuth(event)
  const body = await readBody(event)
  const parsed = autoVideoSchema.safeParse(body)

  if (!parsed.success) {
    throw createError({ statusCode: 400, message: parsed.error.issues[0]?.message || 'Invalid input' })
  }

  const { mediaItemId, basePrompt, audioPrompt, negativePrompt, count, steps, numFrames, width, height, fps, loraStrength, endpoint } = parsed.data
  let image = parsed.data.image || ''

  // If mediaItemId provided, fetch the image from storage
  if (mediaItemId && !image) {
    const db = useDatabase()
    const item = await db.select({ url: mediaItems.url }).from(mediaItems).where(eq(mediaItems.id, mediaItemId)).get()
    if (!item?.url) throw createError({ statusCode: 404, message: 'Image not found' })
    // Fetch the image from the URL and convert to base64
    const resp = await fetch(item.url)
    if (!resp.ok) throw createError({ statusCode: 500, message: 'Failed to fetch image' })
    const buf = await resp.arrayBuffer()
    const uint8 = new Uint8Array(buf)
    let binary = ''
    for (let i = 0; i < uint8.length; i++) binary += String.fromCharCode(uint8[i]!)
    image = btoa(binary)
  }

  if (!image) throw createError({ statusCode: 400, message: 'Image is required' })
  const apiUrl = resolveApiUrl(endpoint)
  const db = useDatabase()
  const now = new Date().toISOString()

  // Create parent generation record
  const genId = crypto.randomUUID()
  await db.insert(generations).values({
    id: genId,
    userId: user.id,
    prompt: basePrompt || 'Auto video from image',
    imageCount: count,
    status: 'processing',
    createdAt: now,
  })

  // Call pod synchronously — the pipeline captions, generates prompts, and queues T2V jobs
  // This may take 20-60s for captioning + prompt generation
  const runpodInput = {
    action: 'image2video_auto',
    image,
    base_prompt: basePrompt,
    audio_prompt: audioPrompt,
    negative_prompt: negativePrompt,
    count,
    steps,
    num_frames: numFrames,
    width,
    height,
    fps,
    lora_strength: loraStrength,
  }

  console.log(`[AutoVideo] Starting pipeline for gen ${genId.slice(0, 8)}, count=${count}`)

  try {
    const result = await callRunPod(runpodInput, apiUrl)

    if (result.error) {
      await db.update(generations).set({ status: 'failed' }).where(eq(generations.id, genId))
      throw createError({ statusCode: 500, message: result.error })
    }

    const output = result.output || {}
    const jobs = output.jobs || []
    const caption = output.caption || ''

    // Create media items for each queued T2V job — they'll be picked up by the polling cron
    const items: any[] = []
    for (const job of jobs) {
      const videoId = crypto.randomUUID()
      await db.insert(mediaItems).values({
        id: videoId,
        generationId: genId,
        type: 'video',
        prompt: job.prompt,
        status: 'processing',
        runpodJobId: job.prompt_id, // ComfyUI prompt_id, not RunPod job
        metadata: JSON.stringify({
          apiUrl,
          autoGenerated: true,
          caption,
          promptIndex: job.index,
          comfyPromptId: job.prompt_id,
        }),
        createdAt: now,
      })
      items.push({
        id: videoId,
        generationId: genId,
        type: 'video',
        prompt: job.prompt,
        status: 'processing',
        runpodJobId: job.prompt_id,
        url: null,
      })
    }

    console.log(`[AutoVideo] ✅ ${items.length} jobs queued for gen ${genId.slice(0, 8)}`)

    return {
      generation: { id: genId, status: 'processing', imageCount: count },
      items,
      caption,
      prompts: jobs.map((j: any) => j.prompt),
      timing: {
        captionSeconds: output.caption_seconds,
        promptSeconds: output.prompt_seconds,
        totalSeconds: output.elapsed_seconds,
      },
    }
  } catch (e: any) {
    if (e.statusCode) throw e
    console.error(`[AutoVideo] Pipeline error:`, e)
    await db.update(generations).set({ status: 'failed' }).where(eq(generations.id, genId))
    throw createError({ statusCode: 500, message: e.message || 'Auto video pipeline failed' })
  }
})
