name = "ai-media-gen"
compatibility_date = "2024-04-05"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "ai-media-gen-db"
database_id = "9a1de542-1861-4a4c-a456-7367915c2dee"
preview_database_id = "DB"
migrations_dir = "drizzle"

[[r2_buckets]]
binding = "MEDIA"
bucket_name = "ai-media-gen-media"
